name: Close PR with spam comment

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'Spam' }}
    runs-on: ubuntu-latest

    steps:
    - name: Close Pull Request
      uses: peter-evans/close-pull@v2
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        comment: "Auto-closing pull request because it's spam"
        delete-branch: true
